# Generated by Django 4.2.17 on 2025-01-19 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thmr_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family_funds_box_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الصندوق'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family_funds_box_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='رقم الصندوق'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='family_funds_regulations',
            field=models.FileField(blank=True, null=True, upload_to='regulations/', verbose_name=' اللائحة الاساسية للصندو'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='الإسم الرباعي'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'National ID must be exactly 10 digits.')], verbose_name='رقم الهوية'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Telephone must be exactly 10 digits.')], verbose_name='رقم الهاتف'),
        ),
    ]
